package me.aap.fermata.addon.stremio.ui.source;

/** Stable, secret-free failures that Android UI can localize. */
public enum SourceUiError {
	NONE,
	CANCELLED,
	CLOSED,
	CONCURRENT_MODIFICATION,
	DUPLICATE_SOURCE,
	INVALID_MANIFEST,
	INVALID_ORDER,
	INVALID_URL,
	NOT_FOUND,
	PERSISTENCE,
	ROLLBACK,
	SECRET_REJECTED,
	SECURE_STORAGE,
	TRANSPORT,
	CLEARTEXT_CONSENT_REQUIRED,
	LAN_CONSENT_REQUIRED,
	UNKNOWN
}
